version: '3.9'
services:
  exif-postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data

  nextjs-app:
    # image: exif-photo-blog:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .env:/app/.env
    ports:
      - '57017:3000'
    depends_on:
      - exif-postgres



