version: '3.9'
services:
  nextjs-app:
    image: exif-photo-blog:latest
    volumes:
      - .env:/app/.env
    ports:
      - '57017:3000'
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data

